allow-branch = ["main"]
consolidate-commits = true
consolidate-pushes = true
dev-version = false
pre-release-commit-message = "chore(release): release new version ğŸ‰"
publish = false
push = false
tag = false
